modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Artemka091102/Explosion/issues"
[[mods]]
modId="explosion"
version="${file.jarVersion}"
displayName="Explosion"
updateJSONURL="https://raw.githubusercontent.com/Artemka091102/Explosion/master/src/main/resources/META-INF/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/explosion"
logoFile="explosion.png"
credits='''

_romanchick_: helps in coding
Pugemon: helps in testing
FlyMaster: teached me modding
'''
authors='''

Artemka091102
'''
description='''
This mod makes blocks degradate after explosion. Write your questions @Artemka091102#6675
'''
[[dependencies.explosion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.15.2]"
    ordering="NONE"
    side="SERVER"
